name: Event details on Issues
on : issues

jobs:
  event_details:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          echo "Event Actor: ${{ github.actor }}"
          echo "Event Repository: ${{ github.repository }}"
          echo "Event Issue Number: ${{ github.event.issue.number }}"
          echo "Event Issue Title: ${{ github.event.issue.title }}"
          echo "Event Issue Body: ${{ github.event.issue.body }}"